version: '3'

services:
  db:
    image: postgres
    container_name: ydzen-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
        - "postgres:/var/lib/postgresql/data"
    networks:
      - ydzen_apinet

  web:
    build: ./
    container_name: ydzen-api
    restart: always
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - ydzen_apinet
    ports:
      - "8001:8000"

volumes:
  postgres:

networks:
  ydzen_apinet:
    external: true