# Generated by Django 4.2 on 2024-07-23 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='post.post'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_marks', to=settings.AUTH_USER_MODEL),
        ),
    ]
